version: '3.8'

services:
  backend:
    build: .
    container_name: eye-disease-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - DEBUG=True
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: eye-disease-detection-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped 